version: "3.9"
services:
  opensearch:
    image: opensearchproject/opensearch:2.15.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock: {soft: -1, hard: -1}
    ports: ["9200:9200"]
    volumes: ["osdata:/usr/share/opensearch/data"]
volumes: { osdata: {} }
